version: '2'

services:
  nginx:
    environment:
      - VIRTUAL_HOST=dylan.simowitz.test,www.dylan.simowitz.test
    restart: on-failure

  ghost:
    restart: on-failure

networks:
  default:
    external:
      name: nginx-proxy
