version: '2'

services:
  nginx:
    environment:
      - VIRTUAL_HOST=dylan.simowitz.test,www.dylan.simowitz.test
    restart: on-failure

  ghost:
    environment:
      - NODE_ENV=development
      - url=http://dylan.simowitz.test/blog/
    restart: on-failure
    volumes:
      - ./blog/data/:/var/lib/ghost/content/data/
      - ./blog/config.development.json:/var/lib/ghost/config.development.json:ro
