version: '2'

services:
  home:
    image: registry.gitlab.simowitz.com/dsimowitz/dylan.simowitz.com
    restart: always
    expose:
      - 80
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:dylan.simowitz.com"
      - "traefik.backend=dylan-home"
      - "traefik.docker.network=web"
      - "traefik.enable=true"

  blog:
    image: ghost:alpine
    restart: always
    environment:
      - NODE_ENV=production
      - url=https://dylan.simowitz.com/blog/
    volumes:
      - ./blog/data/:/var/lib/ghost/content
    expose:
      - 2368
    labels:
      - "traefik.port=2368"
      - "traefik.frontend.rule=Host:dylan.simowitz.com;PathPrefix:/blog"
      - "traefik.backend=dylan-blog"
      - "traefik.docker.network=web"
      - "traefik.enable=true"

  portfolio:
    image: registry.gitlab.simowitz.com/dsimowitz/portfolio
    restart: always
    command: hugo server --watch=false --baseURL=https://dylan.simowitz.com/portfolio --appendPort=false --bind=0.0.0.0 --canonifyURLs --renderToDisk
    expose:
      - 1313
    labels:
      - "traefik.port=1313"
      - "traefik.frontend.rule=Host:dylan.simowitz.com;PathPrefix:/portfolio"
      - "traefik.backend=dylan-portfolio"
      - "traefik.docker.network=web"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: web
